export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';


export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET';

export const CREATE_PRODUCT_REVIEW_REQUEST = 'CREATE_PRODUCT_REVIEW_REQUEST';
export const CREATE_PRODUCT_REVIEW_FAIL = 'CREATE_PRODUCT_REVIEW_FAIL';
export const CREATE_PRODUCT_REVIEW_SUCCESS = 'CREATE_PRODUCT_REVIEW_SUCCESS';
export const CREATE_PRODUCT_REVIEW_RESET = 'CREATE_PRODUCT_REVIEW_RESET';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_RESET = 'ALL_PRODUCTS_RESET';

export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST';
export const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL';
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS';
export const ADMIN_PRODUCTS_RESET = 'ADMIN_PRODUCTS_RESET';

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST';
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_RESET = 'DELETE_IMAGE_RESET';


export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_FAIL = 'CREATE_QUESTION_FAIL';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_RESET = 'CREATE_QUESTION_RESET';

export const CREATE_ANSWER_REQUEST = 'CREATE_ANSWER_REQUEST';
export const CREATE_ANSWER_FAIL = 'CREATE_ANSWER_FAIL';
export const CREATE_ANSWER_SUCCESS = 'CREATE_ANSWER_SUCCESS';
export const CREATE_ANSWER_RESET = 'CREATE_ANSWER_RESET';

export const DELETE_ANSWER_REQUEST = 'DELETE_ANSWER_REQUEST';
export const DELETE_ANSWER_FAIL = 'DELETE_ANSWER_FAIL';
export const DELETE_ANSWER_SUCCESS = 'DELETE_ANSWER_SUCCESS';
export const DELETE_ANSWER_RESET = 'DELETE_ANSWER_RESET';

export const FEATURE_PRODUCTS_REQUEST = 'FEATURE_PRODUCTS_REQUEST';
export const FEATURE_PRODUCTS_FAIL = 'FEATURE_PRODUCTS_FAIL';
export const FEATURE_PRODUCTS_SUCCESS = 'FEATURE_PRODUCTS_SUCCESS';
export const FEATURE_PRODUCTS_RESET = 'FEATURE_PRODUCTS_RESET';





export const CLEAR_ERRORS = 'CLEAR_ERRORS'